LOG_FILE: '/var/log/tcx.log'
LOG_LEVEL: 'INFO'
LOG_FORMAT: '%(asctime)s.%(msecs)03d  %(levelname)s  %(module)s - %(funcName)s: %(message)s'
LOG_DATEFMT: '%Y%m%d %H:%M:%S'

PIN_CONFIG:
    EEPROM_SDA: 0 # required for HAT support
    EEPROM_SCL: 1 # required for HAT support
    ## DEFAULT PIN_CONFIG
    pOT1: 18
    pOT2: 17    # unused but kept for TC4 compatability
    pIO2: 4     # unused but kept for TC4 compatability
